---
- name: "Writes genesis state locally if it not exist"
  become: yes
  become_user: "{{ binance_user_name }}"
  command:
    cmd: "{{ binance_geth_path }} --datadir {{ binance_datadir }} init {{ binance_root }}/genesis.json"
    creates: "{{ binance_datadir }}/geth"

- name: "Create {{ binance_sevice_name }} systemd service"
  template:
    src: binance.service.j2
    dest: "{{ binance_service_dir }}/{{ binance_sevice_name }}.service"
    mode: 0644

- name: "get {{ binance_user_name }} uid"
  getent:
    database: passwd
    key: "{{ binance_user_name }}"
- debug:
    var: getent_passwd['{{ binance_user_name }}'][1]

- name: "Start and enable {{ binance_sevice_name }} service"
  become: true
  become_user: "{{ binance_user_name }}"
  systemd:
    name: "{{ binance_sevice_name }}.service"
    scope: user
    daemon_reload: yes
    enabled: yes
    state: started
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['getent_passwd'][binance_user_name][1] }}"
